spring:
  application:
    name: chat-me-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/chatme
    username: postgres
    password: postgres
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-postgresql.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  docker:
#    compose:
#      enabled: true
#      file: docker-compose.yml

#logging:
#  level:
#    org.springframework.security.web: TRACE
#    org.springframework.security.authentication: DEBUG